### PR TITLE
MVP

### PR DESCRIPTION
**Pull request by bryantee**
Develop branch [deployed on Heroku](https://mysterious-harbor-55179.herokuapp.com/) for testing purposes. <-- sign up here

I'd love for anyone to signup and test it out. You need to use your Github username, but feel free to use a throw away password. It doesn't link to your github profile, it just makes use of the non-authenticated API to bring in public data.

[Issues for Milestone #1](https://github.com/bryantee/GitChain/milestone/1)

Thanks!

### CODE REVIEW

**Comment by rockchalkwushock** [comment]
Bryan looks great! Very nice UI/UX. I was unable to get the application to work in Safari. On both signup and login my dev-tools would show the following error upon submission:

Login Page: `ReferenceError: Can't find variable: fetch - anonymous function - main.js:143`.
Signup Page: `ReferenceError: Can't find variable: fetch - anonymous function - main.js:120`.

I did notice your console.logs show if my passwords matched etc. would be nice to integrate some kind of visual validation or message to the user if their passwords don't match or the GH account is not valid.

Got it working in Chrome with none of the previous issues. When I log out I'm directed to a view that just says `Logout Page`. I'm never actually being logged out though, nor am I being redirected to a home or some kind of landing page. The `Log Out` button/link remains in the log out state. I'm able to go to my profile and still update and see my commits, etc.

I would say it's a good idea to do something with your routes so `Profile` is only visible to an authenticated user and not any average Joe as soon as they land on the page.

Just my 2 cents overall looks great but still has some functionality bugs to be worked out.

**Comment by bryantee** [comment]
Thanks @rockchalkwushock, awesome feedback!

I've still got some work left before I merge.

**Comment by mdfw** [comment]
Just tried it.
Picky things: 
1."Passwword (for GitChain)" should be "Password (for GitChain)"
2. On landing, you are showing the about page (I think) but profile menu is highlighted. Thus, when I clicked on about, nothing happened.

Functionality: I couldn't get signup to work. In console I see `ReferenceError: Can't find variable: fetch` in main.js line 120

**Comment by bryantee** [comment]
Thanks @mdfw. Yeah fetch may be an issue as I don't think Safari yet supports that Web API. Was it Safari you were testing with? Chrome and Firefox seem go for me.

I think I'm going to setup a polyfill like [this](https://github.github.io/fetch/).

**Pull request merged**
